[tox]
envlist =
    py{39,310,311,312,313}-unit
    integration-18
    integration-19
skip_missing_interpreters = true

[testenv]
usedevelop = true
deps =
    pytest
    pytest-cov
setenv =
    PYTHONPATH = {toxinidir}/tests/mock/odoo
commands =
    pytest --cov=pytest_oduit --cov-report=term-missing tests/

[testenv:integration-18]
basepython = python3.12
setenv =
deps =
    pytest
    pytest-cov
    pytest-subtests
    pytest-xdist
passenv =
    PG*
    ODOO_RC
commands_pre =
    python -m pip install "lxml>=5.2.1" lxml_html_clean "Werkzeug==3.0.1" freezegun
    python -m pip install https://github.com/OCA/OCB/archive/18.0.tar.gz
commands =
    pytest --oduit-env {toxinidir}/tests_integration/odoo/.oduit-18.toml --odoo-install=pytest_oduit_test_module --odoo-http {toxinidir}/tests_integration/odoo/addons/pytest_oduit_test_module
    pytest --oduit-env {toxinidir}/tests_integration/odoo/.oduit-18.toml --odoo-install=pytest_oduit_test_module {toxinidir}/tests_integration/odoo/addons/pytest_oduit_test_module

[testenv:integration-19]
basepython = python3.12
setenv =
deps =
    pytest
    pytest-cov
    pytest-subtests
    pytest-xdist
passenv =
    PG*
    ODOO_RC
commands_pre =
    python -m pip install "lxml>=5.2.1" lxml_html_clean "Werkzeug==3.0.1" freezegun
    python -m pip install https://github.com/OCA/OCB/archive/19.0.tar.gz
commands =
    pytest --oduit-env {toxinidir}/tests_integration/odoo/.oduit-19.toml --odoo-install=pytest_oduit_test_module --odoo-http {toxinidir}/tests_integration/odoo/addons/pytest_oduit_test_module
    pytest --oduit-env {toxinidir}/tests_integration/odoo/.oduit-19.toml --odoo-install=pytest_oduit_test_module {toxinidir}/tests_integration/odoo/addons/pytest_oduit_test_module
