name: Odoo Integration Tests
on: [push, pull_request]

jobs:
  odoo-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        odoo-version: ["17.0", "18.0"]
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Checkout Odoo
        uses: actions/checkout@v4
        with:
          repository: odoo/odoo
          ref: ${{ matrix.odoo-version }}
          path: odoo
          fetch-depth: 0
      
      - name: Install Odoo dependencies
        run: |
          pip install -r odoo/requirements.txt
      
      - name: Install pytest-oduit
        run: |
          pip install -e .
      
      - name: Create .oduit.toml configuration
        run: |
          cat > .oduit.toml << 'EOF'
          [binaries]
            odoo_bin = "odoo"
          [odoo_params]
            db_name = "test_db"
            db_host = "localhost"
            db_port = 5432
            db_user = "odoo"
            db_password = "odoo"
            addons_path = ["odoo/addons"]
          EOF
      
      - name: Run pytest tests locally
        run: |
          pytest --verbose --odoo-log-level info --odoo-http odoo/addons/calendar/
