name: Odoo Integration Tests
on: [push, pull_request]

jobs:
  odoo-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        odoo-version: ["17.0", "18.0"]
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Checkout Odoo
        uses: actions/checkout@v4
        with:
          repository: odoo/odoo
          ref: ${{ matrix.odoo-version }}
          path: odoo
          fetch-depth: 0
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            adduser \
            fonts-dejavu-core \
            fonts-inconsolata \
            fonts-font-awesome \
            fonts-roboto-unhinted \
            gsfonts \
            libjs-underscore \
            lsb-base \
            postgresql-client \
            python3-babel \
            python3-chardet \
            python3-cryptography \
            python3-dateutil \
            python3-decorator \
            python3-docutils \
            python3-freezegun \
            python3-geoip2 \
            python3-gevent \
            python3-greenlet \
            python3-idna \
            python3-pil \
            python3-jinja2 \
            python3-libsass \
            python3-lxml-html-clean \
            python3-markupsafe \
            python3-num2words \
            python3-ofxparse \
            python3-passlib \
            python3-polib \
            python3-psutil \
            python3-psycopg2 \
            python3-pydot \
            python3-openssl \
            python3-pypdf2 \
            python3-rjsmin \
            python3-qrcode \
            python3-renderpm \
            python3-reportlab \
            python3-requests \
            python3-stdnum \
            python3-tz \
            python3-urllib3 \
            python3-vobject \
            python3-werkzeug \
            python3-xlsxwriter \
            python3-xlrd \
            python3-zeep \
            python3-ldap
      
      - name: Install Odoo dependencies
        run: |
          pip install -r odoo/requirements.txt
      
      - name: Install pytest-oduit
        run: |
          pip install -e .
      
      - name: Create .oduit.toml configuration
        run: |
          cat > .oduit.toml << 'EOF'
          [binaries]
            odoo_bin = "odoo"
          [odoo_params]
            db_name = "test_db"
            db_host = "localhost"
            db_port = 5432
            db_user = "odoo"
            db_password = "odoo"
            addons_path = ["odoo/addons"]
          EOF
      
      - name: Run pytest tests locally
        run: |
          pytest --verbose --odoo-log-level info --odoo-http odoo/addons/calendar/
