name: Odoo Integration Tests
on: [push, pull_request]

jobs:
  odoo-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    
    strategy:
      matrix:
        odoo-version: ["17.0", "18.0"]
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Build pytest-oduit wheel
        run: |
          pip install build
          python -m build --wheel
      
      - name: Pull Odoo Docker image
        run: docker pull odoo:${{ matrix.odoo-version }}
      
      - name: Start Odoo container
        run: |
          docker run -d \
            --name odoo \
            --network host \
            -v ${{ github.workspace }}:/mnt/pytest-oduit \
            -e HOST=localhost \
            -e USER=odoo \
            -e PASSWORD=odoo \
            odoo:${{ matrix.odoo-version }}
      
      - name: Wait for Odoo to be ready
        run: |
          timeout 120 bash -c 'until docker logs odoo 2>&1 | grep -q "odoo.modules.loading: Modules loaded."; do sleep 2; done' || true
          sleep 5
      
      - name: Install dependencies in container
        run: |
          docker exec --user root odoo apt-get update
          docker exec --user root odoo apt-get install -y python3-pytest unzip
      
      - name: Install pytest-oduit wheel in container
        run: |
          WHEEL_FILE=$(ls dist/*.whl)
          docker exec --user root odoo bash -c "cd /tmp && unzip -q /mnt/pytest-oduit/$WHEEL_FILE && cp -r pytest_oduit.py pytest_oduit-*.dist-info /usr/local/lib/python3/dist-packages/"
      
      - name: Run pytest tests inside container
        run: |
          docker exec odoo pytest --verbose --odoo-log-level info --odoo-http /usr/lib/python3/dist-packages/odoo/addons/calendar/
      
      - name: Show Odoo logs on failure
        if: failure()
        run: docker logs odoo
      
      - name: Stop Odoo container
        if: always()
        run: docker stop odoo && docker rm odoo
